from .verificar_antecedentes_nacionales import verificar_antecedentes_nacionales
from .gestionar_turnos_clases_examenes import gestionar_turnos_clases_examenes
from .validar_asistencia import validar_asistencia
from .validar_examen_practico import validar_examen_practico
from .carga_nacional import carga_nacional
